# Generated by Django 4.2.4 on 2023-08-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='series_series_id',
        ),
        migrations.RemoveField(
            model_name='column',
            name='series_user_id',
        ),
    ]
