# Generated by Django 4.2.4 on 2023-08-14 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('column', '0002_remove_column_series_series_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='uuid',
            new_name='column_id',
        ),
        migrations.AlterField(
            model_name='column',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
