# Generated by Django 4.2.4 on 2023-08-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0004_category_remove_column_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
