# Generated by Django 4.2.4 on 2023-08-14 19:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0005_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'tag1'), (2, 'tag2'), (3, 'tag3'), (4, 'tag4'), (5, 'tag5')], max_length=5, null=True),
        ),
    ]
