# Generated by Django 4.2.4 on 2023-08-15 21:17

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0006_column_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='column',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'tag1'), (1, 'tag2'), (2, 'tag3'), (3, 'tag4'), (4, 'tag5')], max_length=5, null=True),
        ),
    ]
