# Generated by Django 4.2.4 on 2023-08-16 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
        ('column', '0007_column_price_alter_column_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='series_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='series.series'),
        ),
    ]
