# Generated by Django 4.2.2 on 2023-08-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, verbose_name='사용자 고유번호')),
                ('userId', models.CharField(max_length=100, unique=True, verbose_name='사용자 아이디')),
                ('password', models.CharField(max_length=100, verbose_name='사용자 비밀번호')),
                ('userName', models.CharField(max_length=100, verbose_name='사용자 이름')),
                ('email', models.CharField(max_length=100, verbose_name='사용자 이메일')),
                ('phone_number', models.CharField(max_length=30, unique=True, verbose_name='사용자 전화번호')),
                ('birth', models.DateField(verbose_name='사용자 생년월일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
    ]
