# Generated by Django 4.2.4 on 2023-08-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, verbose_name='사용자 고유번호')),
                ('userId', models.CharField(max_length=100, unique=True, verbose_name='사용자 아이디')),
                ('password', models.CharField(max_length=100, verbose_name='사용자 비밀번호')),
                ('userName', models.CharField(max_length=100, verbose_name='사용자 이름')),
                ('email', models.CharField(max_length=100, verbose_name='사용자 이메일')),
                ('phone_number', models.CharField(max_length=30, unique=True, verbose_name='사용자 전화번호')),
                ('birth', models.DateField(verbose_name='사용자 생년월일')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
    ]
