# Generated by Django 4.2.4 on 2023-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='사용자 고유번호'),
        ),
    ]
