# Generated by Django 4.2.4 on 2023-08-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=1000, verbose_name='보유 금액'),
        ),
    ]
