# Generated by Django 4.2.4 on 2023-08-16 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
