# Generated by Django 4.2.4 on 2023-08-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='writerName',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
